language: es
pipeline:
- name: SpacyNLP
  model: es_core_news_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
  entity_recognition: true
  epochs: 50
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
policies:
- name: TEDPolicy
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback

#TokenizerModified.SpacyTokenizer